soundAPI/models.py
from django.db import models


class Artist(models.Model):
    """Model class to record Artist name and ID from Echonest"""
    artist_name = models.CharField(max_length=200)
    artist_id = models.CharField(unique=True, max_length=50)
    # similar relationship is defined.
    related_to = models.ManyToManyField("self", null=True, blank=True,
                                        symmetrical=False)

    def __unicode__(self):
        return u'%s' % self.artist_name

soundAPI/forms.py
from django.forms import Form, CharField, ChoiceField

choice_list = (
    (0, 'all matches'),
    (1, 'exact match'),
    )

class searchForm(Form):
    artist_name = CharField(label="search keyword", max_length=50)
    exact = ChoiceField(label="search type", choices=choice_list)

soundAPI/views.py
# Create your views here.
from django.template import loader, RequestContext, Context
from django.core.paginator import Paginator, PageNotAnInteger
from django.http import HttpResponse, HttpResponseServerError, \
    HttpResponseRedirect

from .forms import searchForm
from .utils import Echoutils


def search(request):
    """ search interface for artist similarity finding """
    if request.is_ajax():
        artist_name = request.GET.get('keyword')
        exact = request.GET.get('exact')
        if exact is None or artist_name is None:
            return HttpResponseServerError("Malformed data submission.")
        echo = Echoutils()
        #import pdb
        #pdb.set_trace()
        results = echo.getArtist(artist_name, exact)
        # sync results to database for now.
        echo.dbSyncArtist(results[0])
        request.session['search_result'] = results
        return HttpResponseRedirect('/search/results/')
    else:
        form = searchForm()
        context = RequestContext(request, {'form': form})
        template = loader.get_template('soundAPI/search.html')
        return HttpResponse(template.render(context))
        

def results(request):
    results = request.session.get('search_result')
    # start paginating the results.
    if type(results) is tuple:
        # print "start paginating the results"
        paginator = Paginator(results[0], 5)
        num = request.GET.get('page_num')
        try:
            res = paginator.page(num)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            res = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 999), deliver last page of results.
            res = paginator.page(paginator.num_pages)
        template = loader.get_template('soundAPI/resultslist.html')
        context = Context({
            'results': res,
            'exact' : results[1],
        })
        return HttpResponse(template.render(context))
    else:
        return HttpResponseServerError('API ERROR')

soundAPI/templates/soundAPI/resultslist.html
<span>
   <p>
    {% if exact %}
        Exact Matches:
    {% else %}
        Partial Matches:
    {% endif %}
    {{results.start_index}} to {{results.end_index}} of total {{results.paginator.count}}
   </p>
</span>
<table class="table">
   <tr>
      <th>Artist</th>
      <th>Hotness</th>
      <th>Echo Nest ID</th>
   </tr>
   {% for result in results %}
   <tr>
      <td>{{ result.name }}</td>
      <td>{{ result.hotttnesss }}</td>
      <td>{{ result.id }}</td>
   </tr>
   {% endfor %}
</table>
<div class="pagination">
   <span class="step-links">
   {% if results.has_previous %}
   <a href="#" name='{{ results.previous_page_number }}'>previous</a>
   {% endif %}
   <span class="current">
   Page {{ results.number }} of {{ results.paginator.num_pages }}.
   </span>
   {% if results.has_next %}
   <a href="#" name='{{ results.next_page_number }}'>next</a>
   {% endif %}
   </span>
</div>

soundAPI/templates/soundAPI/search.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
   <head>
      <title>Econest search Demo</title>
      <link rel="stylesheet" href="{% static "css/libs/bootstrap.min.css" %}">
      <style>
      /* inline css script for evaluation of code should be ideally
      inside an external file*/
      #loadingDiv{
        display: none;
        z-index: 2000;
        position:absolute;
        top:50px;
        left:300px;
      }
      </style>
      <script type="text/javascript" src="http://code.jquery.com/jquery-2.0.0.min.js">
      </script>
      <script type="text/javascript">
        $('document').ready(function(){
            //inline code is for evaluation purpose only.
            // ideally should be contained within a external script file.
            function call_ajax(){
                $.ajax({url:"/", context: document.body,
                       data: "exact=" + $('#id_exact').val()+ "&keyword=" +
                        $('#id_artist_name').val(),
                        beforeSend: function(){
                            $('#loadingDiv').css('display','inline');
                            return true;
                        }
                        })
                        .done(function(data){
                            // success
                            $('#result_list').html(data);
                            $('.step-links a').bind('click', function(evnt){
                                evnt.preventDefault();
                                var page_num = this.name;
                                pageflip_ajax(page_num);
                            });
                        })
                        .always(function(){
                    // done or fail fire this
                            $('#loadingDiv').css('display','none');
                        });
            }
            
            function pageflip_ajax(page_num){
            $.ajax({url:'/search/results/', data: "page_num=" + page_num})
            .done(function(data){
                // populate the html data.
                $('#result_list').html(data);
                $('.step-links a').bind('click', function(evnt){
                        evnt.preventDefault();
                        var page_num = this.name;
                        pageflip_ajax(page_num);
                    });
                });
            }
            
            
            var keytimer = null;
            var timerdelay = 300; //adjust speed in ms var
            var keywordHistory = "";
            
            $('#id_artist_name').bind('keyup change inpemut propertychange',
            function(evnt){
                // fire the ajax after the keyword changes
                // we need to delay a bit to let the user finish typing
                // enter keys may kill the page so disable them.
                var code = evnt.which;
                if (code===13){
                    evnt.preventDefault();
                }
                if (keytimer) {
                //if new key comes before timeout clear it
                clearTimeout(keytimer);
                }
                keytimer = setTimeout(function() {
                    var keydata = jQuery("#id_artist_name").val();
                    if ((keydata.length > 0) && (keywordHistory !== $.trim(keydata)))
                        // as timerdelay is reached timeout occurs, now
                        // fire ajax.
                        {
                        call_ajax();
                        keywordHistory = keydata;
                        }
                    },timerdelay);
            });
            
            $('#id_exact').bind('change', function(){
                // fire the ajax after the keyword changes
                call_ajax();
            });
        });
    </script>
   </head>
   <body>
      <div class="container">
         <p class="row-fluid lead">EchoNest Artist Search</p>
         <form action="" class="searchForm">
            <table>
               <tr>
                  <td> {{ form.exact.label_tag }}{{ form.exact }} </td>
                  <td>{{ form.artist_name.label_tag }}{{ form.artist_name }}</td>
               </tr>
            </table>
         </form>
         <div id="result_list">
         </div>
         <div id="loadingDiv"><img src=" {% static "images/spinner.gif" %}"></div>
      </div>
   </body>
</html>